# -*- coding: utf-8 -*-
"""skin_cancer_streamlit_deployment_final_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUs_t1vXHJ7POYe2433GolVjlfbBPHQP

# Skin Image Classifier — Colab Training + Streamlit Deployment

This notebook trains an accuracy-focused image classifier and creates a portable Streamlit deployment package.

**Important:** the supplied dataset labels are `dermIS`, `dermis`, and `dermquest`. They appear to be source/directory labels, not verified clinical diagnoses. The resulting model should therefore be described as a classifier for these dataset classes, not as a clinically validated skin-cancer diagnostic system.

The notebook is designed so that Streamlit does **not** download the Kaggle dataset or install packages at runtime.
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Google Colab dependencies
# %pip install -q kagglehub tensorflow keras-tuner scikit-learn pandas matplotlib seaborn pillow
print("Dependencies installed.")

# 2. Imports and reproducibility
from pathlib import Path
import json, random, hashlib, zipfile

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image, ImageFile

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import keras_tuner as kt

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, confusion_matrix, f1_score

ImageFile.LOAD_TRUNCATED_IMAGES = True

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

"""## 3. Dataset acquisition"""

# 3. Download dataset
import kagglehub

DATASET_NAME = "fatemehmehrparvar/skin-cancer-detection"

print("Downloading dataset...")
path = kagglehub.dataset_download(DATASET_NAME)
DATASET_ROOT = Path(path)

if not DATASET_ROOT.exists():
    raise FileNotFoundError(f"Dataset directory was not found: {DATASET_ROOT}")

print("Dataset path:", DATASET_ROOT)
print("\nTop-level contents:")
for p in sorted(DATASET_ROOT.iterdir()):
    print(" -", p.name)

# 4. Discover image files and labels
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

records = []
for file in DATASET_ROOT.rglob("*"):
    if file.is_file() and file.suffix.lower() in IMAGE_EXTS:
        rel = file.relative_to(DATASET_ROOT)
        label = rel.parts[0] if len(rel.parts) >= 2 else file.parent.name
        records.append((str(file), label))

df = pd.DataFrame(records, columns=["filepath", "label"])

if df.empty:
    raise RuntimeError("No images found. Check the printed dataset directory.")

df = df.drop_duplicates("filepath").reset_index(drop=True)

print("Total images:", len(df))
print(df["label"].value_counts())
display(df.head())

# 5. Validate images and remove exact duplicates
valid = []
seen = set()

for row in df.itertuples(index=False):
    fp = Path(row.filepath)
    try:
        with Image.open(fp) as im:
            im.verify()
        digest = hashlib.sha256(fp.read_bytes()).hexdigest()
        if digest in seen:
            continue
        seen.add(digest)
        valid.append((row.filepath, row.label))
    except Exception:
        pass

df = pd.DataFrame(valid, columns=["filepath", "label"]).reset_index(drop=True)

print("Valid unique images:", len(df))
print("\nClass distribution:")
print(df["label"].value_counts())

# 6. Stratified train/validation/test split
class_names = sorted(df["label"].unique().tolist())
NUM_CLASSES = len(class_names)
if NUM_CLASSES < 2: raise RuntimeError(f"Expected at least 2 classes, found: {class_names}")
class_counts = df["label"].value_counts()
if (class_counts < 3).any(): raise RuntimeError(f"Every class needs at least 3 images. Small classes: {class_counts[class_counts < 3].to_dict()}")
train_df, temp_df = train_test_split(df, test_size=0.30, stratify=df["label"], random_state=SEED)
val_df, test_df = train_test_split(temp_df, test_size=0.50, stratify=temp_df["label"], random_state=SEED)
class_indices = {name: i for i, name in enumerate(class_names)}
print("Classes:", class_names); print("Train:", len(train_df)); print("Validation:", len(val_df)); print("Test:", len(test_df))

# 7. Class-balanced weights
y_train = train_df["label"].map(class_indices).to_numpy()
weights = compute_class_weight(
    class_weight="balanced",
    classes=np.arange(NUM_CLASSES),
    y=y_train
)
class_weight = {i: float(w) for i, w in enumerate(weights)}

print("Class weights:", class_weight)

"""## 4. Data pipeline and augmentation"""

# 8. tf.data pipeline
IMG_SIZE = (224, 224)
BATCH_SIZE = 16
AUTOTUNE = tf.data.AUTOTUNE

def load_image(path, label):
    image = tf.io.read_file(path)
    image = tf.image.decode_image(image, channels=3, expand_animations=False)
    image.set_shape([None, None, 3])
    image = tf.image.resize(image, IMG_SIZE, antialias=True)
    return tf.cast(image, tf.float32), label

def make_dataset(frame, training=False):
    paths = frame["filepath"].to_numpy(dtype=str)
    labels = frame["label"].map(class_indices).to_numpy(dtype=np.int32)
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training: ds = ds.shuffle(len(frame), seed=SEED, reshuffle_each_iteration=True)
    return ds.map(load_image, num_parallel_calls=AUTOTUNE).batch(BATCH_SIZE).prefetch(AUTOTUNE)

train_ds = make_dataset(train_df, training=True)
val_ds = make_dataset(val_df)
test_ds = make_dataset(test_df)

def make_augmentation():
    return keras.Sequential([
        layers.RandomFlip("horizontal"), layers.RandomRotation(0.08), layers.RandomZoom(0.12),
        layers.RandomTranslation(0.05, 0.05), layers.RandomContrast(0.10)
    ], name="augmentation")

"""## 5. Hyperparameter tuning"""

# 9. Robust EfficientNetV2B0 hyperparameter tuning
# A fresh augmentation layer and backbone are created for every tuner trial.
def build_tunable_model(hp):
    tf.keras.backend.clear_session()
    base = keras.applications.EfficientNetV2B0(include_top=False, weights="imagenet", input_shape=IMG_SIZE+(3,), include_preprocessing=True)
    base.trainable = False
    inputs = keras.Input(shape=IMG_SIZE+(3,), name="image")
    x = make_augmentation()(inputs)
    x = base(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(hp.Float("dropout", 0.2, 0.5, step=0.1))(x)
    x = layers.Dense(hp.Choice("dense_units", [128, 256]), activation="relu")(x)
    x = layers.Dropout(hp.Float("dropout2", 0.1, 0.3, step=0.1))(x)
    outputs = layers.Dense(NUM_CLASSES, activation="softmax", dtype="float32")(x)
    model = keras.Model(inputs, outputs)
    model.compile(optimizer=keras.optimizers.AdamW(
        learning_rate=hp.Float("learning_rate", 1e-4, 2e-3, sampling="log"),
        weight_decay=hp.Float("weight_decay", 1e-6, 1e-4, sampling="log")),
        loss=keras.losses.SparseCategoricalCrossentropy(label_smoothing=0.05),
        metrics=[keras.metrics.SparseCategoricalAccuracy(name="accuracy")])
    return model

tuner = kt.RandomSearch(hypermodel=build_tunable_model, objective=kt.Objective("val_accuracy", direction="max"),
    max_trials=5, executions_per_trial=1, overwrite=True, directory="/content/keras_tuner", project_name="skin_classifier")
print("Starting hyperparameter tuning...")
tuner.search(train_ds, validation_data=val_ds, epochs=6, class_weight=class_weight,
    callbacks=[keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=2, restore_best_weights=True)], verbose=1)
best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]
print("Best hyperparameters:")
for k, v in best_hp.values.items(): print(f"  {k}: {v}")

"""## 6. Training and fine-tuning"""

# 10. Train the best hyperparameter configuration
tf.keras.backend.clear_session()
model = tuner.hypermodel.build(best_hp)
callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=4, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.3, patience=2, min_lr=1e-7),
    keras.callbacks.ModelCheckpoint("/content/best_head.keras", monitor="val_accuracy", save_best_only=True)
]
history = model.fit(train_ds, validation_data=val_ds, epochs=15, class_weight=class_weight, callbacks=callbacks, verbose=1)
if Path("/content/best_head.keras").exists(): model = keras.models.load_model("/content/best_head.keras")
print("Best validation accuracy:", float(max(history.history["val_accuracy"])))

# 11. Fine-tune the last 30% of the pretrained backbone
base_model = next((layer for layer in model.layers if isinstance(layer, keras.Model) and "efficientnet" in layer.name.lower()), None)
if base_model is None: raise RuntimeError(f"EfficientNet backbone not found. Nested models: {[x.name for x in model.layers if isinstance(x, keras.Model)]}")
base_model.trainable = True
start = int(len(base_model.layers) * 0.70)
for i, layer in enumerate(base_model.layers):
    layer.trainable = i >= start
    if isinstance(layer, layers.BatchNormalization): layer.trainable = False
base_lr = float(best_hp.get("learning_rate")); weight_decay = float(best_hp.get("weight_decay"))
model.compile(optimizer=keras.optimizers.AdamW(learning_rate=base_lr*0.1, weight_decay=weight_decay),
    loss=keras.losses.SparseCategoricalCrossentropy(label_smoothing=0.03),
    metrics=[keras.metrics.SparseCategoricalAccuracy(name="accuracy")])
callbacks_ft = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=5, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.3, patience=2, min_lr=1e-8),
    keras.callbacks.ModelCheckpoint("/content/best_finetuned.keras", monitor="val_accuracy", save_best_only=True)
]
history_ft = model.fit(train_ds, validation_data=val_ds, epochs=20, class_weight=class_weight, callbacks=callbacks_ft, verbose=1)
if Path("/content/best_finetuned.keras").exists(): model = keras.models.load_model("/content/best_finetuned.keras")

"""## 7. Test evaluation and TTA"""

# 12. Standard test evaluation
test_probs = model.predict(test_ds, verbose=0)
test_preds = np.argmax(test_probs, axis=1)
test_true = test_df["label"].map(class_indices).to_numpy()

print("Test accuracy:", accuracy_score(test_true, test_preds))
print("Balanced accuracy:", balanced_accuracy_score(test_true, test_preds))
print("Macro F1:", f1_score(test_true, test_preds, average="macro"))

print("\nClassification report:")
print(classification_report(
    test_true, test_preds,
    labels=np.arange(NUM_CLASSES),
    target_names=class_names,
    zero_division=0
))

cm = confusion_matrix(test_true, test_preds, labels=np.arange(NUM_CLASSES))
plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Test Confusion Matrix")
plt.show()

# 13. Horizontal-flip test-time augmentation
def make_flip_dataset(frame):
    paths = frame["filepath"].to_numpy(dtype=str)
    labels = frame["label"].map(class_indices).to_numpy(dtype=np.int32)
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    def loader(path, label):
        image = tf.io.read_file(path)
        image = tf.image.decode_image(image, channels=3, expand_animations=False)
        image.set_shape([None, None, 3])
        image = tf.image.resize(image, IMG_SIZE, antialias=True)
        image = tf.image.flip_left_right(tf.cast(image, tf.float32))
        return image, label
    return ds.map(loader, num_parallel_calls=AUTOTUNE).batch(BATCH_SIZE).prefetch(AUTOTUNE)
flip_ds = make_flip_dataset(test_df)
flip_probs = model.predict(flip_ds, verbose=0)
tta_probs = (test_probs + flip_probs) / 2.0
tta_preds = np.argmax(tta_probs, axis=1)
print("TTA accuracy:", accuracy_score(test_true, tta_preds))
print("TTA balanced accuracy:", balanced_accuracy_score(test_true, tta_preds))
print("TTA macro F1:", f1_score(test_true, tta_preds, average="macro"))

"""## 8. Create the complete Streamlit deployment package"""

# 14. Export a portable Streamlit Cloud deployment package
DEPLOY_DIR = Path("/content/skin_cancer_streamlit_app")
DEPLOY_DIR.mkdir(parents=True, exist_ok=True)

MODEL_PATH = DEPLOY_DIR / "skin_cancer_model.keras"
META_PATH = DEPLOY_DIR / "metadata.json"
APP_PATH = DEPLOY_DIR / "app.py"
REQ_PATH = DEPLOY_DIR / "requirements.txt"
PYTHON_VERSION_PATH = DEPLOY_DIR / ".python-version"
README_PATH = DEPLOY_DIR / "README.md"

print("Final model input shape:", model.input_shape)
print("Final model output shape:", model.output_shape)
model.save(MODEL_PATH)

metadata = {
    "class_names": class_names,
    "image_size": list(IMG_SIZE),
    "num_classes": NUM_CLASSES,
    "model_type": "EfficientNetV2B0_transfer_learning",
    "dataset_name": DATASET_NAME,
    "note": "Dataset labels are source/directory labels and are not clinically validated diagnoses."
}
META_PATH.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

APP_CODE = '''
import json
from pathlib import Path

import numpy as np
import streamlit as st
import tensorflow as tf
from PIL import Image

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "skin_cancer_model.keras"
META_PATH = BASE_DIR / "metadata.json"

st.set_page_config(page_title="Skin Image Classifier", page_icon="🔬")

@st.cache_resource
def load_artifacts():
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Model not found: {MODEL_PATH}")
    if not META_PATH.exists():
        raise FileNotFoundError(f"Metadata not found: {META_PATH}")

    with open(META_PATH, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    model = tf.keras.models.load_model(MODEL_PATH, compile=False)
    return model, metadata

try:
    model, metadata = load_artifacts()
except Exception as exc:
    st.error("The model could not be loaded.")
    st.exception(exc)
    st.stop()

class_names = metadata["class_names"]
img_size = tuple(metadata["image_size"])

st.title("🔬 Skin Image Classifier")
st.warning(
    "Educational/research use only. This model is not a clinically validated "
    "skin-cancer diagnostic device."
)

uploaded_file = st.file_uploader(
    "Upload a skin image",
    type=["jpg", "jpeg", "png", "webp"]
)

if uploaded_file is not None:
    try:
        image = Image.open(uploaded_file).convert("RGB")
        st.image(image, caption="Uploaded image", use_container_width=True)

        image_resized = image.resize(img_size)
        x = np.asarray(image_resized, dtype=np.float32)
        x = np.expand_dims(x, axis=0)

        probabilities = model.predict(x, verbose=0)[0]
        predicted_idx = int(np.argmax(probabilities))
        predicted_class = class_names[predicted_idx]
        confidence = float(probabilities[predicted_idx])

        st.subheader("Prediction")
        st.write(f"**Predicted class:** {predicted_class}")
        st.metric("Model confidence", f"{confidence:.2%}")

        st.subheader("Class probabilities")
        for cls, prob in zip(class_names, probabilities):
            st.progress(float(prob), text=f"{cls}: {float(prob):.2%}")

    except Exception as exc:
        st.error("Could not process the uploaded image.")
        st.exception(exc)

st.caption(
    "Performance may not generalize to other cameras, populations, clinical "
    "settings, or image types."
)
'''

APP_PATH.write_text(APP_CODE.strip() + "\n", encoding="utf-8")

REQS = 'streamlit>=1.40,<2\ntensorflow==2.20.0\nnumpy>=1.26,<2.3\npillow>=10,<12\n'
REQ_PATH.write_text(REQS, encoding="utf-8")

PYTHON_VERSION_PATH.write_text("3.12.10\n", encoding="utf-8")

README = f'''# Streamlit deployment package

Upload these files to the root of your GitHub repository:

- app.py
- skin_cancer_model.keras
- metadata.json
- requirements.txt
- .python-version

Select `app.py` as the Streamlit Cloud main file.

The deployed app does NOT install packages at runtime and does NOT download the Kaggle dataset.

Training-only packages such as matplotlib, seaborn, pandas, scikit-learn, keras-tuner and kagglehub are not imported by app.py.

Classes: {", ".join(class_names)}
Input size: {IMG_SIZE[0]} x {IMG_SIZE[1]}
'''
README_PATH.write_text(README, encoding="utf-8")

print("Deployment package created:")
for p in sorted(DEPLOY_DIR.iterdir()):
    print(" -", p.name)

# 15. Validate deployment files, syntax-check app.py, and create ZIP
import ast
import zipfile

required = [
    DEPLOY_DIR / "app.py",
    DEPLOY_DIR / "skin_cancer_model.keras",
    DEPLOY_DIR / "metadata.json",
    DEPLOY_DIR / "requirements.txt",
    DEPLOY_DIR / ".python-version",
]

missing = [p.name for p in required if not p.exists()]
if missing:
    raise FileNotFoundError(f"Missing deployment files: {missing}")

ast.parse((DEPLOY_DIR / "app.py").read_text(encoding="utf-8"))
print("app.py syntax check: PASSED")

app_text = (DEPLOY_DIR / "app.py").read_text(encoding="utf-8")
for forbidden in ["matplotlib", "seaborn", "pandas", "sklearn", "keras_tuner", "kagglehub"]:
    assert f"import {forbidden}" not in app_text, f"Unexpected deployment import: {forbidden}"
print("Deployment import check: PASSED")

ZIP_PATH = Path("/content/skin_cancer_streamlit_app_fixed.zip")
with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as z:
    for p in DEPLOY_DIR.iterdir():
        if p.is_file():
            z.write(p, arcname=p.name)

print("ZIP created:", ZIP_PATH)
print("Upload the ZIP contents to GitHub, not the ZIP itself.")