# -*- coding: utf-8 -*-
"""skin_cancer_colab_streamlit_final_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vn4nOCu2qfriWttb2LUXenaNevc6OCqZ

# Skin Image Classifier — Final Colab + Streamlit Deployment

This is the final stability-focused version.

Pipeline:
**Kaggle dataset → validation/cleaning → stratified split → class balancing → EfficientNetV2B0 transfer learning → manual hyperparameter tuning → fine-tuning → held-out test evaluation → TTA → Streamlit package.**

The notebook deliberately avoids Keras-Tuner, Matplotlib and Seaborn to reduce dependency/runtime failures. Hyperparameter tuning is performed directly with three controlled configurations.

The generated Streamlit application contains only the runtime dependencies it actually needs and does not download the Kaggle dataset.

**Important:** dataset directory labels are treated as dataset classes and are not clinically validated diagnoses. This project is for educational/research use, not medical diagnosis.
"""

# 1. Google Colab setup — safe TensorFlow bootstrap
# Run this notebook in Google Colab with Runtime -> Change runtime type -> GPU.
#
# Colab normally already contains TensorFlow. We first try the installed
# TensorFlow instead of blindly reinstalling it. If it is missing, install
# a compatible TensorFlow version.

import sys
import subprocess

print("Python:", sys.version)

if sys.version_info >= (3, 14):
    raise RuntimeError(
        "This notebook requires a Python runtime supported by TensorFlow. "
        "Your runtime is Python 3.14. Start a fresh standard Google Colab "
        "runtime (Python 3.12) and run this notebook again."
    )

def ensure_package(package, import_name=None):
    import_name = import_name or package
    try:
        __import__(import_name)
        print(f"{import_name}: already installed")
        return
    except ImportError:
        print(f"{import_name}: installing {package}")

    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", package]
    )

# Only install TensorFlow if it is missing.
ensure_package("tensorflow==2.20.0", "tensorflow")

# Training/data packages.
subprocess.check_call(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "kagglehub",
        "scikit-learn",
        "pandas",
        "pillow",
    ]
)

print("Required packages are ready.")

# 2. Imports and reproducibility

from pathlib import Path
import json
import random
import hashlib
import zipfile
import gc

import numpy as np
import pandas as pd
from PIL import Image, ImageFile

try:
    import tensorflow as tf
except Exception as exc:
    raise RuntimeError(
        "TensorFlow could not be imported. Start a fresh Google Colab "
        "runtime with Python 3.12 and run Cell 1 first."
    ) from exc

from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)

ImageFile.LOAD_TRUNCATED_IMAGES = True

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

gpus = tf.config.list_physical_devices("GPU")

for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError:
        pass

print("TensorFlow:", tf.__version__)
print("GPU(s):", gpus)
print("TensorFlow import: PASSED")

# 3. Runtime validation
print("=== Runtime validation ===")
print("Python:", sys.version.split()[0])
print("TensorFlow:", tf.__version__)
print("Keras:", keras.__version__)
print("GPU(s):", tf.config.list_physical_devices("GPU"))

print("TensorFlow runtime validation: PASSED")

"""## 3. Dataset acquisition"""

# 6. Robust labels and stratified train / validation / test split

df["label"] = (
    df["label"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

df = df[df["label"].ne("")].copy()

class_names = sorted(
    df["label"].dropna().unique().tolist(),
    key=lambda x: x.lower(),
)

NUM_CLASSES = len(class_names)

if NUM_CLASSES < 2:
    raise RuntimeError(
        f"At least 2 classes are required. "
        f"Found {NUM_CLASSES}: {class_names}"
    )

class_counts = df["label"].value_counts()

print("Number of classes:", NUM_CLASSES)
print("Class names:", class_names)
print("\nImages per class:")
print(class_counts.sort_index())

if int(class_counts.min()) < 6:
    raise RuntimeError(
        "Every class needs at least 6 valid images for the "
        "70/15/15 stratified split. Small classes: "
        + str(class_counts[class_counts < 6].to_dict())
    )

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["label"],
    random_state=SEED,
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=SEED,
)

class_indices = {
    name: index
    for index, name in enumerate(class_names)
}

print("\nTrain:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

# 6. Robust stratified train / validation / test split
class_names = sorted(df["label"].unique().tolist())
NUM_CLASSES = len(class_names)

if NUM_CLASSES < 2:
    raise RuntimeError(f"At least 2 classes are required. Found: {class_names}")

class_counts = df["label"].value_counts()

if int(class_counts.min()) < 6:
    raise RuntimeError(
        "Every class needs at least 6 valid images for a 70/15/15 "
        "stratified split. Small classes: "
        + str(class_counts[class_counts < 6].to_dict())
    )

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["label"],
    random_state=SEED,
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=SEED,
)

class_indices = {name: i for i, name in enumerate(class_names)}

print("Classes:", class_names)
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

# 5. Validate images and remove exact duplicates
valid = []
seen = set()

for row in df.itertuples(index=False):
    fp = Path(row.filepath)
    try:
        with Image.open(fp) as im:
            im.verify()
        digest = hashlib.sha256(fp.read_bytes()).hexdigest()
        if digest in seen:
            continue
        seen.add(digest)
        valid.append((row.filepath, row.label))
    except Exception:
        pass

df = pd.DataFrame(valid, columns=["filepath", "label"]).reset_index(drop=True)

print("Valid unique images:", len(df))
print("\nClass distribution:")
print(df["label"].value_counts())

# 6. Stratified train/validation/test split
class_names = sorted(df["label"].unique().tolist())
NUM_CLASSES = len(class_names)
if NUM_CLASSES < 2: raise RuntimeError(f"Expected at least 2 classes, found: {class_names}")
class_counts = df["label"].value_counts()
if (class_counts < 3).any(): raise RuntimeError(f"Every class needs at least 3 images. Small classes: {class_counts[class_counts < 3].to_dict()}")
train_df, temp_df = train_test_split(df, test_size=0.30, stratify=df["label"], random_state=SEED)
val_df, test_df = train_test_split(temp_df, test_size=0.50, stratify=temp_df["label"], random_state=SEED)
class_indices = {name: i for i, name in enumerate(class_names)}
print("Classes:", class_names); print("Train:", len(train_df)); print("Validation:", len(val_df)); print("Test:", len(test_df))

# 7. Class-balanced weights
y_train = train_df["label"].map(class_indices).to_numpy()
weights = compute_class_weight(
    class_weight="balanced",
    classes=np.arange(NUM_CLASSES),
    y=y_train
)
class_weight = {i: float(w) for i, w in enumerate(weights)}

print("Class weights:", class_weight)

"""# 9. Stable manual hyperparameter tuning
# This replaces Keras-Tuner to avoid version/session compatibility errors.

def make_augmentation():
    return keras.Sequential(
        [
            layers.RandomFlip("horizontal"),
            layers.RandomRotation(0.08),
            layers.RandomZoom(0.12),
            layers.RandomTranslation(0.05, 0.05),
            layers.RandomContrast(0.10),
        ],
        name="augmentation",
    )

def build_model(
    learning_rate,
    weight_decay,
    dropout,
    dense_units,
    label_smoothing=0.05,
):
    tf.keras.backend.clear_session()
    gc.collect()

    base = keras.applications.EfficientNetV2B0(
        include_top=False,
        weights="imagenet",
        input_shape=IMG_SIZE + (3,),
        include_preprocessing=True,
        name="efficientnetv2b0",
    )
    base.trainable = False

    inputs = keras.Input(
        shape=IMG_SIZE + (3,),
        name="image",
    )

    x = make_augmentation()(inputs)
    x = base(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(dropout)(x)
    x = layers.Dense(dense_units, activation="relu")(x)
    x = layers.Dropout(0.20)(x)

    outputs = layers.Dense(
        NUM_CLASSES,
        activation="softmax",
        dtype="float32",
        name="prediction",
    )(x)

    model = keras.Model(inputs, outputs)

    model.compile(
        optimizer=keras.optimizers.AdamW(
            learning_rate=learning_rate,
            weight_decay=weight_decay,
        ),
        loss=keras.losses.SparseCategoricalCrossentropy(
            label_smoothing=label_smoothing
        ),
        metrics=[
            keras.metrics.SparseCategoricalAccuracy(name="accuracy")
        ],
    )
    return model

SEARCH_SPACE = [
    {
        "learning_rate": 1e-3,
        "weight_decay": 1e-5,
        "dropout": 0.30,
        "dense_units": 128,
    },
    {
        "learning_rate": 5e-4,
        "weight_decay": 1e-5,
        "dropout": 0.40,
        "dense_units": 256,
    },
    {
        "learning_rate": 3e-4,
        "weight_decay": 1e-4,
        "dropout": 0.30,
        "dense_units": 256,
    },
]

tuning_results = []
best_val_accuracy = -np.inf
best_config = None

for trial_no, config in enumerate(SEARCH_SPACE, start=1):
    print("\n" + "=" * 70)
    print(f"Hyperparameter trial {trial_no}/{len(SEARCH_SPACE)}")
    print(config)
    print("=" * 70)

    candidate = build_model(**config)

    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor="val_accuracy",
            patience=2,
            restore_best_weights=True,
            mode="max",
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.3,
            patience=1,
            min_lr=1e-7,
        ),
    ]

    history_trial = candidate.fit(
        train_ds,
        validation_data=val_ds,
        epochs=6,
        class_weight=class_weight,
        callbacks=callbacks,
        verbose=1,
    )

    trial_accuracy = float(max(history_trial.history["val_accuracy"]))

    result = dict(config)
    result["best_val_accuracy"] = trial_accuracy
    tuning_results.append(result)

    print(
        f"Trial {trial_no} best validation accuracy: "
        f"{trial_accuracy:.4f}"
    )

    if trial_accuracy > best_val_accuracy:
        best_val_accuracy = trial_accuracy
        best_config = dict(config)

    del candidate
    del history_trial
    gc.collect()
    tf.keras.backend.clear_session()

tuning_df = pd.DataFrame(tuning_results).sort_values(
    "best_val_accuracy",
    ascending=False,
).reset_index(drop=True)

display(tuning_df)

if best_config is None:
    raise RuntimeError("No valid hyperparameter configuration was selected.")

print("Selected configuration:", best_config)
print("Best validation accuracy:", best_val_accuracy)

"""

# 10. Train the selected hyperparameter configuration
tf.keras.backend.clear_session()
gc.collect()

model = build_model(**best_config)

callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=4,
        restore_best_weights=True,
        mode="max",
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.3,
        patience=2,
        min_lr=1e-7,
    ),
    keras.callbacks.ModelCheckpoint(
        "/content/best_head.keras",
        monitor="val_accuracy",
        save_best_only=True,
        mode="max",
    ),
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    class_weight=class_weight,
    callbacks=callbacks,
    verbose=1,
)

checkpoint = Path("/content/best_head.keras")

if checkpoint.exists():
    model = keras.models.load_model(
        checkpoint,
        compile=False,
    )

print(
    "Best head-training validation accuracy:",
    float(max(history.history["val_accuracy"]))
)

"""# 11. Fine-tune the final 30% of EfficientNetV2B0
base_model = model.get_layer("efficientnetv2b0")
base_model.trainable = True

fine_tune_start = int(len(base_model.layers) * 0.70)

for i, layer in enumerate(base_model.layers):
    layer.trainable = i >= fine_tune_start

    if isinstance(layer, layers.BatchNormalization):
        layer.trainable = False

fine_tune_lr = float(best_config["learning_rate"]) * 0.1
fine_tune_weight_decay = float(best_config["weight_decay"])

model.compile(
    optimizer=keras.optimizers.AdamW(
        learning_rate=fine_tune_lr,
        weight_decay=fine_tune_weight_decay,
    ),
    loss=keras.losses.SparseCategoricalCrossentropy(
        label_smoothing=0.03
    ),
    metrics=[
        keras.metrics.SparseCategoricalAccuracy(name="accuracy")
    ],
)

fine_tune_callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=5,
        restore_best_weights=True,
        mode="max",
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.3,
        patience=2,
        min_lr=1e-8,
    ),
    keras.callbacks.ModelCheckpoint(
        "/content/best_finetuned.keras",
        monitor="val_accuracy",
        save_best_only=True,
        mode="max",
    ),
]

history_ft = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    class_weight=class_weight,
    callbacks=fine_tune_callbacks,
    verbose=1,
)

fine_checkpoint = Path("/content/best_finetuned.keras")

if fine_checkpoint.exists():
    model = keras.models.load_model(
        fine_checkpoint,
        compile=False,
    )

print("Fine-tuning complete.")
print("Input shape:", model.input_shape)
print("Output shape:", model.output_shape)

"""

# 12. Final held-out test evaluation
test_probs = model.predict(test_ds, verbose=0)
test_preds = np.argmax(test_probs, axis=1)
test_true = test_df["label"].map(class_indices).to_numpy(dtype=np.int32)

test_accuracy = accuracy_score(test_true, test_preds)
test_balanced_accuracy = balanced_accuracy_score(
    test_true,
    test_preds,
)
test_macro_f1 = f1_score(
    test_true,
    test_preds,
    average="macro",
)

print(f"Test accuracy:     {test_accuracy:.4f}")
print(f"Balanced accuracy: {test_balanced_accuracy:.4f}")
print(f"Macro F1:          {test_macro_f1:.4f}")

print("\nClassification report:")
print(
    classification_report(
        test_true,
        test_preds,
        labels=np.arange(NUM_CLASSES),
        target_names=class_names,
        zero_division=0,
    )
)

print("\nConfusion matrix:")
cm = confusion_matrix(
    test_true,
    test_preds,
    labels=np.arange(NUM_CLASSES),
)

display(
    pd.DataFrame(
        cm,
        index=[f"True: {x}" for x in class_names],
        columns=[f"Pred: {x}" for x in class_names],
    )
)

"""# 13. Horizontal-flip Test-Time Augmentation
def make_flip_dataset(frame):
    paths = frame["filepath"].to_numpy(dtype=str)
    labels = frame["label"].map(class_indices).to_numpy(dtype=np.int32)

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    def loader(path, label):
        image_bytes = tf.io.read_file(path)
        image = tf.image.decode_image(
            image_bytes,
            channels=3,
            expand_animations=False,
        )
        image.set_shape([None, None, 3])
        image = tf.image.resize(
            image,
            IMG_SIZE,
            method="bilinear",
            antialias=True,
        )
        image = tf.cast(image, tf.float32)
        image = tf.image.flip_left_right(image)
        return image, label

    return (
        ds.map(loader, num_parallel_calls=AUTOTUNE)
        .batch(BATCH_SIZE)
        .prefetch(AUTOTUNE)
    )

flip_ds = make_flip_dataset(test_df)
flip_probs = model.predict(flip_ds, verbose=0)

tta_probs = (test_probs + flip_probs) / 2.0
tta_preds = np.argmax(tta_probs, axis=1)

tta_accuracy = accuracy_score(test_true, tta_preds)
tta_balanced_accuracy = balanced_accuracy_score(
    test_true,
    tta_preds,
)
tta_macro_f1 = f1_score(
    test_true,
    tta_preds,
    average="macro",
)

print(f"TTA accuracy:           {tta_accuracy:.4f}")
print(f"TTA balanced accuracy: {tta_balanced_accuracy:.4f}")
print(f"TTA macro F1:           {tta_macro_f1:.4f}")

"""

# 10. Train the best hyperparameter configuration
tf.keras.backend.clear_session()
model = tuner.hypermodel.build(best_hp)
callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=4, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.3, patience=2, min_lr=1e-7),
    keras.callbacks.ModelCheckpoint("/content/best_head.keras", monitor="val_accuracy", save_best_only=True)
]
history = model.fit(train_ds, validation_data=val_ds, epochs=15, class_weight=class_weight, callbacks=callbacks, verbose=1)
if Path("/content/best_head.keras").exists(): model = keras.models.load_model("/content/best_head.keras")
print("Best validation accuracy:", float(max(history.history["val_accuracy"])))

# 11. Fine-tune the last 30% of the pretrained backbone
base_model = next((layer for layer in model.layers if isinstance(layer, keras.Model) and "efficientnet" in layer.name.lower()), None)
if base_model is None: raise RuntimeError(f"EfficientNet backbone not found. Nested models: {[x.name for x in model.layers if isinstance(x, keras.Model)]}")
base_model.trainable = True
start = int(len(base_model.layers) * 0.70)
for i, layer in enumerate(base_model.layers):
    layer.trainable = i >= start
    if isinstance(layer, layers.BatchNormalization): layer.trainable = False
base_lr = float(best_hp.get("learning_rate")); weight_decay = float(best_hp.get("weight_decay"))
model.compile(optimizer=keras.optimizers.AdamW(learning_rate=base_lr*0.1, weight_decay=weight_decay),
    loss=keras.losses.SparseCategoricalCrossentropy(label_smoothing=0.03),
    metrics=[keras.metrics.SparseCategoricalAccuracy(name="accuracy")])
callbacks_ft = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=5, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.3, patience=2, min_lr=1e-8),
    keras.callbacks.ModelCheckpoint("/content/best_finetuned.keras", monitor="val_accuracy", save_best_only=True)
]
history_ft = model.fit(train_ds, validation_data=val_ds, epochs=20, class_weight=class_weight, callbacks=callbacks_ft, verbose=1)
if Path("/content/best_finetuned.keras").exists(): model = keras.models.load_model("/content/best_finetuned.keras")

"""## 7. Test evaluation and TTA"""

# 12. Standard test evaluation
test_probs = model.predict(test_ds, verbose=0)
test_preds = np.argmax(test_probs, axis=1)
test_true = test_df["label"].map(class_indices).to_numpy()

print("Test accuracy:", accuracy_score(test_true, test_preds))
print("Balanced accuracy:", balanced_accuracy_score(test_true, test_preds))
print("Macro F1:", f1_score(test_true, test_preds, average="macro"))

print("\nClassification report:")
print(classification_report(
    test_true, test_preds,
    labels=np.arange(NUM_CLASSES),
    target_names=class_names,
    zero_division=0
))

cm = confusion_matrix(test_true, test_preds, labels=np.arange(NUM_CLASSES))
plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Test Confusion Matrix")
plt.show()

# 13. Horizontal-flip test-time augmentation
def make_flip_dataset(frame):
    paths = frame["filepath"].to_numpy(dtype=str)
    labels = frame["label"].map(class_indices).to_numpy(dtype=np.int32)
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    def loader(path, label):
        image = tf.io.read_file(path)
        image = tf.image.decode_image(image, channels=3, expand_animations=False)
        image.set_shape([None, None, 3])
        image = tf.image.resize(image, IMG_SIZE, antialias=True)
        image = tf.image.flip_left_right(tf.cast(image, tf.float32))
        return image, label
    return ds.map(loader, num_parallel_calls=AUTOTUNE).batch(BATCH_SIZE).prefetch(AUTOTUNE)
flip_ds = make_flip_dataset(test_df)
flip_probs = model.predict(flip_ds, verbose=0)
tta_probs = (test_probs + flip_probs) / 2.0
tta_preds = np.argmax(tta_probs, axis=1)
print("TTA accuracy:", accuracy_score(test_true, tta_preds))
print("TTA balanced accuracy:", balanced_accuracy_score(test_true, tta_preds))
print("TTA macro F1:", f1_score(test_true, tta_preds, average="macro"))

"""## 8. Create the complete Streamlit deployment package"""

# 14. Export a portable Streamlit Cloud deployment package
DEPLOY_DIR = Path("/content/skin_cancer_streamlit_app")
DEPLOY_DIR.mkdir(parents=True, exist_ok=True)

MODEL_PATH = DEPLOY_DIR / "skin_cancer_model.keras"
META_PATH = DEPLOY_DIR / "metadata.json"
APP_PATH = DEPLOY_DIR / "app.py"
REQ_PATH = DEPLOY_DIR / "requirements.txt"
PYTHON_VERSION_PATH = DEPLOY_DIR / ".python-version"
README_PATH = DEPLOY_DIR / "README.md"

print("Final model input shape:", model.input_shape)
print("Final model output shape:", model.output_shape)
model.save(MODEL_PATH)

metadata = {
    "class_names": class_names,
    "image_size": list(IMG_SIZE),
    "num_classes": NUM_CLASSES,
    "model_type": "EfficientNetV2B0_transfer_learning",
    "dataset_name": DATASET_NAME,
    "note": "Dataset labels are source/directory labels and are not clinically validated diagnoses."
}
META_PATH.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

APP_CODE = '''
import json
from pathlib import Path

import numpy as np
import streamlit as st
import tensorflow as tf
from PIL import Image

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "skin_cancer_model.keras"
META_PATH = BASE_DIR / "metadata.json"

st.set_page_config(page_title="Skin Image Classifier", page_icon="🔬")

@st.cache_resource
def load_artifacts():
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Model not found: {MODEL_PATH}")
    if not META_PATH.exists():
        raise FileNotFoundError(f"Metadata not found: {META_PATH}")

    with open(META_PATH, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    model = tf.keras.models.load_model(MODEL_PATH, compile=False)
    return model, metadata

try:
    model, metadata = load_artifacts()
except Exception as exc:
    st.error("The model could not be loaded.")
    st.exception(exc)
    st.stop()

class_names = metadata["class_names"]
img_size = tuple(metadata["image_size"])

st.title("🔬 Skin Image Classifier")
st.warning(
    "Educational/research use only. This model is not a clinically validated "
    "skin-cancer diagnostic device."
)

uploaded_file = st.file_uploader(
    "Upload a skin image",
    type=["jpg", "jpeg", "png", "webp"]
)

if uploaded_file is not None:
    try:
        image = Image.open(uploaded_file).convert("RGB")
        st.image(image, caption="Uploaded image", use_container_width=True)

        image_resized = image.resize(img_size)
        x = np.asarray(image_resized, dtype=np.float32)
        x = np.expand_dims(x, axis=0)

        probabilities = model.predict(x, verbose=0)[0]
        predicted_idx = int(np.argmax(probabilities))
        predicted_class = class_names[predicted_idx]
        confidence = float(probabilities[predicted_idx])

        st.subheader("Prediction")
        st.write(f"**Predicted class:** {predicted_class}")
        st.metric("Model confidence", f"{confidence:.2%}")

        st.subheader("Class probabilities")
        for cls, prob in zip(class_names, probabilities):
            st.progress(float(prob), text=f"{cls}: {float(prob):.2%}")

    except Exception as exc:
        st.error("Could not process the uploaded image.")
        st.exception(exc)

st.caption(
    "Performance may not generalize to other cameras, populations, clinical "
    "settings, or image types."
)
'''

APP_PATH.write_text(APP_CODE.strip() + "\n", encoding="utf-8")

REQS = "streamlit>=1.40,<2\ntensorflow==2.20.0\nnumpy>=1.26,<2.3\npillow>=10,<12\n"
REQ_PATH.write_text(REQS, encoding="utf-8")

PYTHON_VERSION_PATH.write_text("3.12.10\n", encoding="utf-8")

README = f'''# Streamlit deployment package

Upload these files to the root of your GitHub repository:

- app.py
- skin_cancer_model.keras
- metadata.json
- requirements.txt
- .python-version

Select `app.py` as the Streamlit Cloud main file.

The deployed app does NOT install packages at runtime and does NOT download the Kaggle dataset.

Training-only packages such as matplotlib, seaborn, pandas, scikit-learn, keras-tuner and kagglehub are not imported by app.py.

Classes: {", ".join(class_names)}
Input size: {IMG_SIZE[0]} x {IMG_SIZE[1]}
'''
README_PATH.write_text(README, encoding="utf-8")

print("Deployment package created:")
for p in sorted(DEPLOY_DIR.iterdir()):
    print(" -", p.name)

# 15. Validate deployment files, syntax-check app.py, and create ZIP
import ast
import zipfile

required = [
    DEPLOY_DIR / "app.py",
    DEPLOY_DIR / "skin_cancer_model.keras",
    DEPLOY_DIR / "metadata.json",
    DEPLOY_DIR / "requirements.txt",
    DEPLOY_DIR / ".python-version",
]

missing = [p.name for p in required if not p.exists()]
if missing:
    raise FileNotFoundError(f"Missing deployment files: {missing}")

ast.parse((DEPLOY_DIR / "app.py").read_text(encoding="utf-8"))
print("app.py syntax check: PASSED")

app_text = (DEPLOY_DIR / "app.py").read_text(encoding="utf-8")
for forbidden in ["matplotlib", "seaborn", "pandas", "sklearn", "keras_tuner", "kagglehub"]:
    assert f"import {forbidden}" not in app_text, f"Unexpected deployment import: {forbidden}"
print("Deployment import check: PASSED")

ZIP_PATH = Path("/content/skin_cancer_streamlit_app_fixed.zip")
with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as z:
    for p in DEPLOY_DIR.iterdir():
        if p.is_file():
            z.write(p, arcname=p.name)

print("ZIP created:", ZIP_PATH)
print("Upload the ZIP contents to GitHub, not the ZIP itself.")